@echo off
echo Limpiando el proyecto Flutter...
flutter clean
echo Limpiando caché de Gradle...
cd android
gradlew clean
cd ..
echo Limpiando caché de Pub...
flutter pub cache clean --force
echo Obteniendo dependencias...
flutter pub get
echo Reconstruyendo el proyecto...
flutter build apk --debug
echo Proceso completado!
pause 