name: edificio_app
description: "Aplicación para gestionar inquilinos de un edificio"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.2
  uuid: ^4.3.3
  intl: ^0.20.2
  shared_preferences: ^2.2.2
  path_provider: ^2.0.15
  path: ^1.8.3
  image_picker: ^1.0.7
  flutter_pdfview: ^1.3.2
  open_file: ^3.5.4
  pdf: ^3.10.7
  logger: ^2.0.2+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true 