name: edificio_app
description: "Aplicación para gestionar inquilinos de un edificio"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.2
  uuid: ^4.3.3
  intl: ^0.20.2
  shared_preferences: ^2.3.2
  path_provider: ^2.0.15
  path: ^1.8.3
  image_picker: ^1.0.7
  flutter_pdfview: ^1.3.2
  open_file: ^3.5.4
  pdf: ^3.10.7
  logger: ^2.0.2+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true
  assets:
    - assets/icon/

# Configuración para flutter_launcher_icons
flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icon/app_icon.png"
  min_sdk_android: 21
  remove_alpha_ios: true
  adaptive_icon_background: "#FFFFFF" # Fondo blanco
  adaptive_icon_foreground: "assets/icon/app_icon_foreground.png"
  # Configuración para ajustar el tamaño
  adaptive_icon_foreground_scale_factor: 0.45 # Reduce el tamaño al 45%
  image_path_android: "assets/icon/app_icon.png"
  image_path_ios: "assets/icon/app_icon.png" 