name: edificio_app
description: "Aplicación para gestionar inquilinos de un edificio"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.2
  uuid: ^3.0.7
  shared_preferences: ^2.2.2
  intl: ^0.20.2
  pdf: ^3.11.3
  path_provider: ^2.1.5
  open_file: ^3.5.10

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true 